# Generated by Django 4.2.7 on 2023-12-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='meal_type',
            field=models.CharField(choices=[('starters', 'Starters'), ('main_course', 'Main Course'), ('desserts', 'Desserts'), ('drink', 'Drink')], max_length=200),
        ),
    ]
